### PR TITLE
Use new fernet

### PR DESCRIPTION
**Pull request by derwolfe**

### CODE REVIEW

**Comment by derwolfe** [comment]
Previous PR was #59

**Comment by ehashman** [comment]
Got an error on fetch now :s

```
16-05-12 15:00:59 rackbox INFO [cloudpassage-lib.core] - fetching new auth token for 00e44e29
May 12, 2016 3:00:59 PM clojure.tools.logging$eval420$fn__424 invoke
SEVERE: error in stream handler
java.lang.AbstractMethodError: io.netty.util.concurrent.MultithreadEventExecutorGroup.newChild(Ljava/util/concurrent/ThreadFactory;[Ljava/lang/Object;)Lio/netty/util/concurrent/EventExecutor;
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:64)
...
```

**Comment by derwolfe** [comment]
How did you produce this?

**Comment by derwolfe** [comment]
Just running?

**Comment by ehashman** [comment]
`(cloudpassage-lib.scans/fim-report! id token)`, can share you some API info if that helps.

**Comment by ehashman** [comment]
yay it works now \o/ no warnings

**Pull request merged**
